mex -v pclfeature.cpp ...
    -I"z:\pro\pcl\include\pcl-1.6" ...
    -I"z:\pro\Boost\include"...
    -I"z:\pro\Eigen\include"...
    -I"z:\pro\flann\include" ...
    LINKFLAGS="$LINKFLAGS ...
    /LIBPATH:z:\pro\pcl\lib ...
    /LIBPATH:z:\pro\boost\lib ...
    pcl_common_release.lib ...
    pcl_features_release.lib ...
    pcl_kdtree_release.lib ...
    pcl_search_release.lib"